# Generated by Django 5.1 on 2024-08-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
